services:
  web:
    # Construye la imagen usando tu Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # Mapea el puerto 8000 del contenedor al 8000 del host
    ports:
      - "8000:8000"
    # Monta tu código y datos: así no necesitas rebuild al cambiar .py
    volumes:
      - .:/app           # tu código fuente
      - ./data:/app/data # tu carpeta de datos
      - ./models:/app/models
    # Comando para arrancar el servidor con recarga on-the-fly
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
